version: "3.4"
services:
  csharp: #docker run --rm -it -v ${PWD}:/work -w /work -p 5000:5000 aimvector/csharp:1.0.0 /bin/sh
    container_name: dotnetdocker
    image: absoft/dotnetdocker:0.0.1
    build:
      context: ./src
      target: debug
      network: host
    volumes:
    - ./src/:/work/
    devices:
    - /dev/ttyUSB0:/dev/ttyUSB0


